services:
  - type: web
    name: logforge-api
    runtime: node
    rootDir: .
    plan: starter
    buildCommand: corepack enable && pnpm install --frozen-lockfile && pnpm --filter api build
    startCommand: pnpm --filter api start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20

  - type: web
    name: logforge-web
    runtime: node
    rootDir: .
    plan: starter
    buildCommand: corepack enable && pnpm install --frozen-lockfile && pnpm --filter web build
    startCommand: pnpm --filter web start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
